spring.application.name=fraud-service
server.port=4006

spring.datasource.url=jdbc:postgresql://localhost:5436/fraud_db
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.hostname=localhost
eureka.instance.prefer-ip-address=false
eureka.instance.instance-id=${spring.application.name}:${server.port}
eureka.instance.non-secure-port=${server.port}
eureka.instance.secure-port-enabled=false
eureka.instance.ip-address=127.0.0.1
eureka.instance.appname=${spring.application.name}

spring.data.redis.host=localhost
spring.data.redis.port=6379


spring.kafka.bootstrap-servers=localhost:9092

spring.kafka.topics.fraud-requests=fraud.requests
spring.kafka.topics.fraud-results=fraud.results
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

spring.kafka.consumer.fraud.group-id=fraud-service-group
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer

spring.kafka.consumer.properties.spring.json.use.type.headers=false
spring.kafka.consumer.properties.spring.json.trusted.packages=*

# Actuator Management Endpoints
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always

# Logging Levels
logging.level.root=INFO
logging.level.com.*=DEBUG
logging.level.org.springframework.kafka=DEBUG

# Logging Pattern
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n
